version: '2'
services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
  auth:
    image: esolutionsacademy/auth-georgeb:1
    ports:
      - "9999:9999"
  discovery:
    image: esolutionsacademy/discovery-georgeb:1
  gateway:
    image: esolutionsacademy/gateway-georgeb:1
    ports:
      - "8080:8080"
    links:
      - discovery:discovery
    environment:
      DISCOVERY: discovery
  store:
    image: esolutionsacademy/store-georgeb:1
    links:
      - discovery:discovery
      - zookeeper:zk
      - kafka:kafka
    environment: 
      DISCOVERY: discovery
      KAFKA: kafka
      ZOOKEEPER: zk
  inventory:
    image: esolutionsacademy/inventory-georgeb:1
    links:
      - discovery:discovery
      - zookeeper:zk
      - kafka:kafka
    environment: 
      DISCOVERY: discovery
      KAFKA: kafka
      ZOOKEEPER: zk
      
